# Generated by Django 2.2.2 on 2019-07-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_guestbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='nickname',
            field=models.CharField(max_length=20),
        ),
    ]
